// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutusDocumentDataSlicesSlice = GuestArtistsSlice | PermanentStaffSlice;

/**
 * Content for AboutUs documents
 */
interface AboutusDocumentData {
  /**
   * Slice Zone field in *AboutUs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutusDocumentDataSlicesSlice>; /**
   * Meta Title field in *AboutUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: aboutus.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AboutUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: aboutus.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AboutUs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * AboutUs document from Prismic
 *
 * - **API ID**: `aboutus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutusDocumentData>,
    "aboutus",
    Lang
  >;

type HomeDocumentDataSlicesSlice = PortfolioSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type WorkDocumentDataSlicesSlice = Works2Slice;

/**
 * Content for work documents
 */
interface WorkDocumentData {
  /**
   * Slice Zone field in *work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice>; /**
   * Meta Title field in *work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: work.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: work.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes = AboutusDocument | HomeDocument | WorkDocument;

/**
 * Default variation for AboutUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *AboutUs*
 */
type AboutUsSliceVariation = AboutUsSliceDefault;

/**
 * AboutUs Shared Slice
 *
 * - **API ID**: `about_us`
 * - **Description**: AboutUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutUsSlice = prismic.SharedSlice<
  "about_us",
  AboutUsSliceVariation
>;

/**
 * Item in *GuestArtists → Default → Primary → artists*
 */
export interface GuestArtistsSliceDefaultPrimaryArtistsItem {
  /**
   * name field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * category field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * schedule field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].schedule
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  schedule: prismic.KeyTextField;

  /**
   * instagram field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].instagram
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram: prismic.KeyTextField;

  /**
   * picture field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].picture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  picture: prismic.ImageField<never>;

  /**
   * bio field in *GuestArtists → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[].bio
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bio: prismic.KeyTextField;
}

/**
 * Primary content in *GuestArtists → Default → Primary*
 */
export interface GuestArtistsSliceDefaultPrimary {
  /**
   * artists field in *GuestArtists → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: guest_artists.default.primary.artists[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  artists: prismic.GroupField<
    Simplify<GuestArtistsSliceDefaultPrimaryArtistsItem>
  >;
}

/**
 * Default variation for GuestArtists Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuestArtistsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GuestArtistsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GuestArtists*
 */
type GuestArtistsSliceVariation = GuestArtistsSliceDefault;

/**
 * GuestArtists Shared Slice
 *
 * - **API ID**: `guest_artists`
 * - **Description**: GuestArtists
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GuestArtistsSlice = prismic.SharedSlice<
  "guest_artists",
  GuestArtistsSliceVariation
>;

/**
 * Item in *PermanentStaff → Default → Primary → artists*
 */
export interface PermanentStaffSliceDefaultPrimaryArtistsItem {
  /**
   * name field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * category field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * experience field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].experience
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  experience: prismic.KeyTextField;

  /**
   * bio field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].bio
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bio: prismic.KeyTextField;

  /**
   * instagram field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].instagram
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram: prismic.KeyTextField;

  /**
   * picture field in *PermanentStaff → Default → Primary → artists*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[].picture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Primary content in *PermanentStaff → Default → Primary*
 */
export interface PermanentStaffSliceDefaultPrimary {
  /**
   * artists field in *PermanentStaff → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: permanent_staff.default.primary.artists[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  artists: prismic.GroupField<
    Simplify<PermanentStaffSliceDefaultPrimaryArtistsItem>
  >;
}

/**
 * Default variation for PermanentStaff Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PermanentStaffSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PermanentStaffSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PermanentStaff*
 */
type PermanentStaffSliceVariation = PermanentStaffSliceDefault;

/**
 * PermanentStaff Shared Slice
 *
 * - **API ID**: `permanent_staff`
 * - **Description**: PermanentStaff
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PermanentStaffSlice = prismic.SharedSlice<
  "permanent_staff",
  PermanentStaffSliceVariation
>;

/**
 * Item in *Portfolio → Default → Primary → imagenes*
 */
export interface PortfolioSliceDefaultPrimaryImagenesItem {
  /**
   * media field in *Portfolio → Default → Primary → imagenes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.imagenes[].media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;

  /**
   * title field in *Portfolio → Default → Primary → imagenes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.imagenes[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Portfolio → Default → Primary → imagenes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.imagenes[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Portfolio → Default → Primary*
 */
export interface PortfolioSliceDefaultPrimary {
  /**
   * imagenes field in *Portfolio → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.default.primary.imagenes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  imagenes: prismic.GroupField<
    Simplify<PortfolioSliceDefaultPrimaryImagenesItem>
  >;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PortfolioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Portfolio*
 */
type PortfolioSliceVariation = PortfolioSliceDefault;

/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PortfolioSlice = prismic.SharedSlice<
  "portfolio",
  PortfolioSliceVariation
>;

/**
 * Item in *Works2 → Default → Primary → works*
 */
export interface Works2SliceDefaultPrimaryWorksItem {
  /**
   * picture field in *Works2 → Default → Primary → works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works2.default.primary.works[].picture
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  picture: prismic.ImageField<never>;

  /**
   * title field in *Works2 → Default → Primary → works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works2.default.primary.works[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Works2 → Default → Primary → works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works2.default.primary.works[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * heading field in *Works2 → Default → Primary → works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works2.default.primary.works[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *Works2 → Default → Primary*
 */
export interface Works2SliceDefaultPrimary {
  /**
   * works field in *Works2 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: works2.default.primary.works[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  works: prismic.GroupField<Simplify<Works2SliceDefaultPrimaryWorksItem>>;
}

/**
 * Default variation for Works2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Works2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Works2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Works2*
 */
type Works2SliceVariation = Works2SliceDefault;

/**
 * Works2 Shared Slice
 *
 * - **API ID**: `works2`
 * - **Description**: Works2
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Works2Slice = prismic.SharedSlice<"works2", Works2SliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutusDocument,
      AboutusDocumentData,
      AboutusDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsSlice,
      AboutUsSliceVariation,
      AboutUsSliceDefault,
      GuestArtistsSlice,
      GuestArtistsSliceDefaultPrimaryArtistsItem,
      GuestArtistsSliceDefaultPrimary,
      GuestArtistsSliceVariation,
      GuestArtistsSliceDefault,
      PermanentStaffSlice,
      PermanentStaffSliceDefaultPrimaryArtistsItem,
      PermanentStaffSliceDefaultPrimary,
      PermanentStaffSliceVariation,
      PermanentStaffSliceDefault,
      PortfolioSlice,
      PortfolioSliceDefaultPrimaryImagenesItem,
      PortfolioSliceDefaultPrimary,
      PortfolioSliceVariation,
      PortfolioSliceDefault,
      Works2Slice,
      Works2SliceDefaultPrimaryWorksItem,
      Works2SliceDefaultPrimary,
      Works2SliceVariation,
      Works2SliceDefault,
    };
  }
}
