// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  portfolio: dynamic(() => import("./Portfolio")),
  works2: dynamic(() => import("./Works2")),
};
